apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: insights-puptoo
  name: insights-puptoo
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: platform-component-tester
  name: platform-component-tester
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: insights-puptoo
  name: insights-puptoo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: insights-puptoo:latest
  postCommit: {}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/RedHatInsights/insights-puptoo.git
  strategy:
    sourceStrategy:
      env:
      - name: ENABLE_PIPENV
        value: "true"
      from:
        kind: ImageStreamTag
        name: python-36-rhel7:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: platform-component-tester
  name: platform-component-tester
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: platform-component-tester:latest
  postCommit: {}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/RedHatInsights/platform-component-tester.git
      ref: master
  strategy:
    sourceStrategy:
      env:
      - name: ENABLE_PIPENV
        value: "true"
      from:
        kind: ImageStreamTag
        name: python-36-rhel7:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: insights-puptoo
  name: insights-puptoo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: insights-puptoo
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: insights-puptoo
        deploymentconfig: insights-puptoo
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: platform-mq-kafka-bootstrap.platform-mq.svc:9092
        - name: LOG_LEVEL
          value: DEBUG
        image: image-registry.openshift-image-registry.svc:5000/buildfactory/insights-puptoo:latest
        imagePullPolicy: Always
        name: insights-puptoo
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - insights-puptoo
      from:
        kind: ImageStreamTag
        name: insights-puptoo:latest
        namespace: sadams
    type: ImageChange
  - type: ConfigChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-consumer
  name: test-consumer
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: test-consumer
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-consumer
        deploymentconfig: test-consumer
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: platform-mq-kafka-bootstrap.platform-mq.svc:9092
        - name: COMPONENT
          value: pup
        - name: ROLE
          value: consume
        image: image-registry.openshift-image-registry.svc:5000/sadams/platform-component-tester:latest
        imagePullPolicy: Always
        name: test-consumer
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - test-consumer
      from:
        kind: ImageStreamTag
        name: platform-component-tester:latest
        namespace: sadams
    type: ImageChange
  - type: ConfigChange
